# This rule is not used by the project vyos-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over vyos.vyos.kubebuilder.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vyos-operator
    app.kubernetes.io/managed-by: kustomize
  name: firewallrule-admin-role
rules:
- apiGroups:
  - vyos.vyos.kubebuilder.io
  resources:
  - firewallrules
  verbs:
  - '*'
- apiGroups:
  - vyos.vyos.kubebuilder.io
  resources:
  - firewallrules/status
  verbs:
  - get
